server:
  port: 8085

#Cloud
spring:
  application:
    name: finance-ai-service
  cloud:
    discovery:
      enabled: true
    openfeign:
      httpclient:
        hc5:
          enabled: true
  main:
    allow-circular-references: true

  #Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5435/finance_ai_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#OpenAI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        model: gpt-4o-mini
      audio:
        transcription:
          model: whisper-1
        speech:
          model: tts-1
          voice: alloy


#Discovery-Server
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      register-with-eureka: true
      fetch-registry: true
  instance:
    prefer-ip-address: true



